name: Tests
on:
  push:
    branches: [master]
    paths-ignore:
      - '.github/**'
  pull_request:
    paths-ignore:
      - '.github/**'


jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ['3.8', '3.9', '3.10']
      fail-fast: false

    steps:
      - uses: actions/checkout@v2
      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install
        run: |
          python -m pip install --upgrade pip
          pip install -e .
          pip install tox tox-gh-actions
      - name: Run tox on ${{ matrix.os }} with Python version ${{ matrix.python-version }}
        run: tox
      - name: "Upload coverage to Codecov"
        if: matrix.python-version == 3.9  # Only upload coverage once per run
        uses: codecov/codecov-action@v2
        with:
          fail_ci_if_error: true
          token: ${{ secrets.CODECOV_TOKEN }}
